'use client'

import { Inter } from 'next/font/google'
import { IconProvider, DEFAULT_ICON_CONFIGS } from '@icon-park/react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const IconConfig = { ...DEFAULT_ICON_CONFIGS, prefix: 'icon' }

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <IconProvider value={IconConfig}>
      <html lang="en" className='w-full h-full'>
        <body className={`${inter.className} w-full h-full overflow-hidden bg-white dark:bg-black dark:text-white`}>{children}</body>
      </html>
    </IconProvider>
  )
}
